### ISSUE TITLE
Ender Dragon does not spawn

### ISSUE THREAD

**Issue by SirJerric** [slicedlime/Distancing#19] opened 2020-08-26 03:45 UTC
Every time I have entered the end (lane 4 or lane 84 sampled) in five different seeds, I have had no ender dragon and no native exit portal "nest". 

Removal of the call to check_end_exits allowed the dragon and "nest" to spawn.

**Comment by NeunEinser** [comment] 2020-08-26 12:04
I tested this and it seems to be caused by setting an end portal in the first tick the end is loaded.
Having a tick function with only `execute as @a[nbt={Dimension: "minecraft:the_end"}] at @s run setblock ~ 64 0 end_portal` reproduced the issue for me.

This could be fixed by checking if there is an end portal in the center. This can be checked by seeing if the following command succeeds: `clone -3 0 -3 3 255 3 -3 0 -3 filtered minecraft:end_portal move` (this clones all end portals in the column where the end portal usually generates to themselves. If there are no end portals, it will fail with the message "no blocks were cloned")

**Closed as completed** 2020-08-30 10:53 UTC
